### ISSUE TITLE
Tabs / Orbit slider: content editing handles throws error when trying to add new content

### ISSUE THREAD

**Issue by ryzy** [million12/M12.Foundation#23]
While in CC in Tabs, you can add 1st content (when the handle has default position `inside`).
Then try to add another content (now the position will be `after`) and you'll get
`Uncaught TypeError: Cannot read property 'options' of undefined InsertNodePanel.js:48 `

Note: **adding it via structure tree panel works.**

##### See the screenshots for details

![screen shot 2015-04-11 at 15 00 43](https://cloud.githubusercontent.com/assets/994940/7101666/e34bf6e4-e05b-11e4-9675-db09cd746568.png)

![screen shot 2015-04-11 at 15 03 45](https://cloud.githubusercontent.com/assets/994940/7101672/faf6d458-e05b-11e4-9055-da9ecf5436fe.png)

**Comment by ryzy** [comment]
PS. AFAIR I had the same issue when I tried to extend CC before you start work on the topic `extendable-contentcollections`, so it's not necessarily related...

**Comment by ryzy** [comment]
Same issue in Orbit Slider, after refactoring in similar way - see #25

**Comment by dimaip** [comment]
Taking care of it.
