### ISSUE TITLE
[BUG] TopBar home link ignores dimensions

### ISSUE THREAD

**Issue by soee** [million12/M12.Foundation#44]
Home link in TopBar NodeType always links to default dimension because href attribute is hardcoded to '/'. We should use neos viehelper to link to root node in current dimensions. There are 2 options:

`<neos:link.node node="~">text</neos:link.node>`
or
`<neos:link.node node="{site}">text</neos:link.node>`

**Comment by ryzy** [comment]
Merged, thanks a lot Marcin!
