### ISSUE TITLE
Home link in TopBar NodeType should be optional

### ISSUE THREAD

**Issue by soee** [million12/M12.Foundation#46]
TopBar NodeType can be used in various ways. When inserted into ContentCollection we can set (or not) home link text through inspector. When this value is empty than link is not generated and this is fine.

Problem is when we define TopBar as a childNode. For example:

```php
'TYPO3.Neos.NodeTypes:Page':
  childNodes:
    navigation:
      type: 'M12.Foundation:TopBar'
```

now the Home link is always generated because of this condition in TypoScript (Resources/Private/TypoScript/Prototypes/Navigation.ts2):

`topBarTitle = ${isDocumentContext ? q(site).property('title') : q(node).property('topBarTitle')}`

(page title is always set and we are in Document context).

Maybe some checkbox in element inspector would be a better option do define if we want or not Home link in TopBar?

**Comment by ryzy** [comment]
I'm happy with inspector checkbox. Next PR from you? ;-) If not, I can handle that in the next couple of days.

**Comment by soee** [comment]
@ryzy Sure, i can do it :)

**Comment by ryzy** [comment]
OK, after 2nd read/thought:

Why do you insert TopBar via childNodes? It doesn't really make sense - you'll have as many menu instances as pages. You should do that from TS. And you'll hit some other configuration issues anyway with such an approach.

```
			menu = M12.Foundation:TopBar {
				entryLevel = 1
				topBarTitle >
            }
```
That works just fine.
