### ISSUE TITLE
Cache issue in Content References

### ISSUE THREAD

**Issue by ryzy** [million12/M12.Foundation#54]
When you change referenced node(s), content rendered by `Content References` is not updated.

`TYPO3.Neos.NodeTypes:ContentReferences` does NOT have any @cache entry… But I guess it would have to have it, moreover, with some rules to invalidate it when referenced nodes have changed (i.e. nodes listed in `TYPO3.Neos.NodeTypes:ContentReferences.properties`)?

**Comment by dimaip** [comment]
It's a Neos bug. Review here: https://review.typo3.org/#/q/topic:content-references-cache

**Comment by soee** [comment]
Hi, so this can be now closed as this patches are in Neos beta 6?

**Comment by ryzy** [comment]
True, resolved by https://review.typo3.org/#/c/41508/ and https://review.typo3.org/#/c/41510/

**Comment by ryzy** [comment]
Thanks @dimaip for contributing these patches!
