### ISSUE TITLE
Accordion: all items should be inactive by default

### ISSUE THREAD

**Issue by soee** [million12/M12.Foundation#58]
The main purpose of using accordion is to hide each item content. At the moment if we add new item it's property "Make the accordion item active" is checked by default and it forces us to click on it each time we want to disable it.

I think in most cases only one item will be active so it would be much better to make the mentioned option disabled by default. Thanks! :)

**Comment by ryzy** [comment]
I'll check that - the idea was to have *only the 1st* item active by default. If the rest of them is active as well, that's a bug.. ;) Thanks for reporting... and feel free send PR if you dug where's the problem.

**Comment by soee** [comment]
This is fixed in 1.x. Closing it.
