### ISSUE TITLE
Update README.md with information about migrtion to 1.x

### ISSUE THREAD

**Issue by soee** [million12/M12.Foundation#62]
There should be **Upgrade** section in README.md file with detailed description how to upgrade to latest version from older one. For example upgrade from 0.2 => 1.x.

Such upgrade instruction should contain command that will change package version in composer.json, command to update composer packages, command to flush cache (for Development and Production context), command to run node migration as it is required.

**Comment by ryzy** [comment]
@soee do you want to commit to do it? Otherwise I'm going to close that one, doesn't make sense if no one is interested in doing it...
