### ISSUE TITLE
Linked buttons have url always set to #

### ISSUE THREAD

**Issue by soee** [million12/M12.Foundation#63]
In button prototyping we have:
```
prototype(M12.Foundation:ButtonLinkAbstract) < prototype(M12.Foundation:Content) {
	url = ${q(node).property('url')}
	url.@process.01 = TYPO3.Neos:ConvertUris
	# Prevents links being clickable while in Neos back-end. 
	# Note: when user provided an url, we need to keep sth in `url`, because it affects the rendering
	# (<a> instead of <button>). Therefore we use @process and replace it with '#' instead of
	# using @if and just skipping processing completely.
	url.@process.99 = ${node.context.currentRenderingMode.edit && value ? '#' : value }
	@override.url = ${this.url}
	...
}
```

This process:
`url.@process.99 = ${node.context.currentRenderingMode.edit && value ? '#' : value }` 
doesn't work anymore from what i see and our links don't have valid urls in live workspace.

Maybe something like this should be used:
`url.@process.99 = ${documentNode.context.inBackend && value ? '#' : value }`

More details https://review.typo3.org/#/c/37363/

**Comment by ryzy** [comment]
Fixed in https://github.com/million12/M12.Foundation/commit/6b29c150cdb31651d609927dfb119ceaefb4dedf
