### ISSUE TITLE
GridRow nolonger creates childnodes

### ISSUE THREAD

**Issue by svparijs** [million12/M12.Foundation#66]
I'm on Neos 2.0.5 and the latest M12.Foundation. For some reason when adding a GridRow to a contentcollection it does not create a row structure for me. 

(This was a missing TYPO3CR migration, after the migration the already existing content is loaded again) When I try to load a already created content structure Grid Row I get a Invalid nodetype error, this might be related...

Anyway I'm gonna dig into the issue but somebody might have run into this issue aswel. Help is welcome of course!

**Comment by ryzy** [comment]
Hi Sebastiaan - fixed in https://github.com/million12/M12.Foundation/commit/f55949482b90d1b7924825ca17096b8e893aab93

thanks for reporting / reminding about it ;)
