### ISSUE TITLE
Typoscript Parser Error

### ISSUE THREAD

**Issue by simonschaufi** [million12/M12.Foundation#68]
I get a parser error in this line:

https://github.com/million12/M12.Foundation/blob/master/Resources/Private/TypoScript/Neos/Image.ts2#L38

with Neos: "typo3/neos": "~2.0.0"

**Comment by dimaip** [comment]
Yeah multiline eel is only in 2.1. Bump requirements?

**Comment by simonschaufi** [comment]
well, the composer.json does't say anything about a dependency to EEL 2.1. Therefor I would expect it also runs in 2.0.

**Comment by dimaip** [comment]
Yeah, that's what I meant, we should update package requirements

**Comment by ryzy** [comment]
@simonschaufi sorry about that, I missed that completely when making this change.

I tagged `v1.0.0` somewhere before that change, as that was pretty stable release.
And then tagged the latest commit with `v1.1.0`. See https://github.com/million12/M12.Foundation/releases

Hope it helps.
